# Generated by Django 4.2.8 on 2023-12-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webSite", "0004_passwordresetcodes"),
    ]

    operations = [
        migrations.DeleteModel(name="Passwordresetcodes",),
    ]
